---
openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  "/api/v1/data/upload":
    post:
      summary: Upload Data
      description: Upload pdf file and processing it
      operationId: upload_data_api_v1_data_upload_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              "$ref": "#/components/schemas/Body_upload_data_api_v1_data_upload_post"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/v1/nlp/index/search":
    post:
      summary: Search Index
      operationId: search_index_api_v1_nlp_index_search_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SearchRequest"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    Body_upload_data_api_v1_data_upload_post:
      properties:
        file:
          type: string
          format: binary
          title: File
      type: object
      required:
      - file
      title: Body_upload_data_api_v1_data_upload_post
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    SearchRequest:
      properties:
        text:
          type: string
          title: Text
        limit:
          anyOf:
          - type: integer
          - type: 'null'
          title: Limit
          default: 5
      type: object
      required:
      - text
      title: SearchRequest
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
